---
- name: Wait until connection is available
  ansible.builtin.wait_for_connection:

- name: Turn on HTTPS listener
  ansible.windows.win_powershell:
    script: "{{ lookup('file', 'winrm_https.ps1') }}"

- name: Set timezone
  ansible.windows.win_shell: >-
    Set-TimeZone -Name "{{ ocpv_vm_timezone.windows }}"

- name: Set up Ansible user
  ansible.windows.win_user:
    name: ansible
    fullname: Ansible
    password: "{{ ocpv_vm_user_win_password }}"
    groups:
      - Administrators
    groups_action: add

- name: Disable UAC filtering for local accounts
  ansible.windows.win_shell: >-
    New-ItemProperty
    -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System"
    -Name "LocalAccountTokenFilterPolicy" -Value 1 -PropertyType DWord -Force

- name: Reset built-in Administrator password and disable it
  ansible.windows.win_user:
    name: Administrator
    password: "{{ lookup('password', '/dev/null', seed=ocpv_vm_name) }}"
    account_disabled: true
